// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD41K62_VxhOLKnBI2blx_XLAGTrL8NS_8',
    appId: '1:429753156561:web:6912a53c6b2ff23e2956f0',
    messagingSenderId: '429753156561',
    projectId: 'flutter-assignment-2-ca560',
    authDomain: 'flutter-assignment-2-ca560.firebaseapp.com',
    storageBucket: 'flutter-assignment-2-ca560.firebasestorage.app',
    measurementId: 'G-50RF0QPSXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCNHfiIZFBVNE4QNgk7niLFbA9sZKavGE',
    appId: '1:429753156561:android:587d38130f70c2122956f0',
    messagingSenderId: '429753156561',
    projectId: 'flutter-assignment-2-ca560',
    storageBucket: 'flutter-assignment-2-ca560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBOqNU-ZDM0CCzpQeCLYSPhao7aKJvKGE',
    appId: '1:429753156561:ios:42f5769f923a87682956f0',
    messagingSenderId: '429753156561',
    projectId: 'flutter-assignment-2-ca560',
    storageBucket: 'flutter-assignment-2-ca560.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBOqNU-ZDM0CCzpQeCLYSPhao7aKJvKGE',
    appId: '1:429753156561:ios:42f5769f923a87682956f0',
    messagingSenderId: '429753156561',
    projectId: 'flutter-assignment-2-ca560',
    storageBucket: 'flutter-assignment-2-ca560.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD41K62_VxhOLKnBI2blx_XLAGTrL8NS_8',
    appId: '1:429753156561:web:68472c090ffbb07c2956f0',
    messagingSenderId: '429753156561',
    projectId: 'flutter-assignment-2-ca560',
    authDomain: 'flutter-assignment-2-ca560.firebaseapp.com',
    storageBucket: 'flutter-assignment-2-ca560.firebasestorage.app',
    measurementId: 'G-HL0TDWZCZ7',
  );
}
